import { Play, Sparkles, Target, Zap, Globe } from 'lucide-react';
import { useAppContext } from '../context/AppContext';

export default function Home() {
  const { navigateTo } = useAppContext();

  return (
    <div className="flex-1 flex flex-col p-6 space-y-24">
      {/* Hero Section */}
      <section className="flex flex-col items-center justify-center text-center mt-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="max-w-3xl space-y-8">
          <div className="inline-flex items-center space-x-2 bg-surface-dark border border-brand-deep rounded-full px-4 py-1.5 text-sm text-brand-neon font-medium shadow-[0_0_15px_rgba(217,70,239,0.2)]">
            <Sparkles size={16} />
            <span>Next-Generation AI Game Generation</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight">
            Create games with <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-neon-light to-brand-neon">
              Intelligent AI
            </span>
          </h1>
          
          <p className="text-xl text-gray-400 max-w-2xl mx-auto leading-relaxed">
            Describe your vision, set your parameters, and let Croevo AI craft your game from the ground up. The future of game development is here.
          </p>
          
          <div className="pt-8">
            <button 
              onClick={() => navigateTo('lab')}
              className="group relative inline-flex items-center justify-center px-8 py-4 font-bold text-background-black bg-gradient-to-r from-brand-neon to-brand-neon-light rounded-full hover:from-brand-neon-light hover:to-brand-neon-light transition-all duration-300 hover:scale-105 shadow-[0_0_40px_-10px_rgba(217,70,239,0.5)]"
            >
              <span className="mr-2">Start Building</span>
              <Play className="group-hover:translate-x-1 transition-transform" size={20} fill="currentColor" />
            </button>
          </div>
        </div>
      </section>

      {/* About Section */}
      <section className="max-w-7xl mx-auto w-full space-y-20 pb-20">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          {/* Mission */}
          <div className="p-8 bg-surface-dark border border-brand-deep rounded-3xl shadow-xl hover:border-brand-neon/30 transition-colors">
            <div className="w-12 h-12 bg-brand-deep rounded-xl flex items-center justify-center mb-6">
              <Target className="text-brand-neon" size={24} />
            </div>
            <h3 className="text-2xl font-bold mb-4 text-white">Our Mission</h3>
            <p className="text-gray-400 leading-relaxed">
              We aim to empower creators of all skill levels by drastically reducing the friction of game development. Croevo AI bridges the gap between imagination and execution, turning raw concepts into fully playable realities within minutes.
            </p>
          </div>

          {/* NATAD Tech */}
          <div className="p-8 bg-surface-dark border border-brand-deep rounded-3xl shadow-xl hover:border-brand-neon/30 transition-colors">
            <div className="w-12 h-12 bg-brand-deep rounded-xl flex items-center justify-center mb-6">
              <Zap className="text-brand-neon" size={24} />
            </div>
            <h3 className="text-2xl font-bold mb-4 text-white">Powered by NATAD Tech</h3>
            <p className="text-gray-400 leading-relaxed">
              At the core of Croevo AI lies NATAD Tech—a neural analysis and procedural generation engine. It intelligently parses your conversational input to construct optimized logic, high-fidelity assets, and robust core loops, dynamically estimating generation costs.
            </p>
          </div>
        </div>

        {/* Community Showcase */}
        <div>
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-brand-deep text-brand-neon mb-6 shadow-[0_0_20px_rgba(217,70,239,0.3)]">
              <Globe size={32} />
            </div>
            <h2 className="text-3xl md:text-4xl font-extrabold mb-4">Community Showcase</h2>
            <p className="text-gray-400">Glimpse the premium creations generated by Croevo AI.</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="group relative overflow-hidden rounded-2xl border border-brand-deep aspect-video bg-surface-mid">
              <img src="/concept_2.jpg" alt="Fantasy RPG Concept" className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-700 opacity-80 group-hover:opacity-100" />
              <div className="absolute inset-0 bg-gradient-to-t from-background-black to-transparent opacity-80" />
              <div className="absolute bottom-4 left-4">
                <p className="font-bold text-white text-lg drop-shadow-md">Voidseeker RPG</p>
                <p className="text-brand-neon text-sm">Generated in 12 mins</p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-2xl border border-brand-deep aspect-video bg-surface-mid">
              <img src="/concept_3.jpg" alt="Cyberpunk Concept" className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-700 opacity-80 group-hover:opacity-100" />
              <div className="absolute inset-0 bg-gradient-to-t from-background-black to-transparent opacity-80" />
              <div className="absolute bottom-4 left-4">
                <p className="font-bold text-white text-lg drop-shadow-md">Neo-Kyoto Racing</p>
                <p className="text-brand-neon text-sm">Generated in 15 mins</p>
              </div>
            </div>
            <div className="group relative overflow-hidden rounded-2xl border border-brand-deep aspect-video bg-surface-mid flex items-center justify-center">
              <div className="absolute inset-0 bg-brand-deep/20 backdrop-blur-sm" />
              <div className="text-center relative z-10 p-6">
                <Sparkles className="mx-auto mb-3 text-brand-neon" size={32} />
                <p className="font-bold text-white text-lg">Your Next Game</p>
                <p className="text-gray-400 text-sm">Start building today</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
